version: '3.3'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/12/main/
    env_file:
      - foodgram/.env
  django:
    build: .
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000" 
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - foodgram/.env
  nginx:
    image: nginx:1.19.6
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static
      - ./media:/var/www/media
      - ./logs:/var/www/logs
      
    ports:
      - "8080:80"
    depends_on:
      - django

volumes:
  postgres_data:
  static_value:
  media_value:
  