# Generated by Django 3.0.5 on 2021-04-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredients',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tagsrecipe',
            unique_together=set(),
        ),
    ]
