# Generated by Django 3.0.5 on 2021-03-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210227_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
